Select 
A.Entity,
A.hits.page.hostname,
A.PostalCode as PostalCode,
A.device.operatingSystem as App,
B.ShopID as ShopID,
Count(DISTINCT A.session_id) as NumBrowse,
Count(DISTINCT B.session_id) as NumRestLoaded,
Count(DISTINCT C.session_id) as NumBought
FROM 
(
Select CONCAT(fullVisitorId, STRING(visitId)) as session_id,
hits.appInfo.appName as Entity,
device.operatingSystem,
hits.page.hostname,
last( hits.eventInfo.eventLabel) as PostalCode
From
TABLE_DATE_RANGE([bcd---clickdelivery:110725090.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bcd---clickdelivery:110732352.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bcd---clickdelivery:110731583.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bdj---damejidlo:119446073.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bdj---damejidlo:134274409.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bdj---damejidlo:134277906.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bdt---baedaltong:119448537.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bdt---baedaltong:119446726.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bdt---baedaltong:119444732.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([befbcg---efood-clickdelivery:111421313.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([befbcg---efood-clickdelivery:111422525.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([befbcg---efood-clickdelivery:111391265.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bfa---foodarena:120655247.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bhh---hungryhouse:110965184.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bhh---hungryhouse:110974286.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bhh---hungryhouse:110981659.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([blh---lieferheld:107101250.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([blh---lieferheld:38642300.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([blh---lieferheld:116747487.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bmj---mjam:13244151.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bmj---mjam:117608936.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bmj---mjam:117591065.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bop---onlinepizza:111057681.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bop---onlinepizza:111053874.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bop---onlinepizza:110474939.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpi---pizzade:109893332.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpi---pizzade:107156186.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpi---pizzade:116747870.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpo---pizzaonline:110480720.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpo---pizzaonline:110470289.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpo---pizzaonline:110477448.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpp---pizzaportal:116858697.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpp---pizzaportal:111070353.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpp---pizzaportal:118750618.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpy---pedidosya:110190327.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpy---pedidosya:110191523.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpy---pedidosya:110187139.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bta---talabat:108646433.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bta---talabat:109362366.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([byy---yogiyo-dhh:109287188.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([byy---yogiyo-dhh:108587309.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([byy---yogiyo-dhh:110796642.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY")))
where 
hits.eventInfo.eventAction = 'shop_list.loaded' 
group by 1,2,3,4 ) A left join
(
Select CONCAT(fullVisitorId, STRING(visitId)) as session_id,
last( hits.eventInfo.eventLabel) as ShopID,
count(Distinct hits.eventInfo.eventLabel) as NumStoresViewed
From
TABLE_DATE_RANGE([bcd---clickdelivery:110725090.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bcd---clickdelivery:110732352.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bcd---clickdelivery:110731583.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bdj---damejidlo:119446073.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bdj---damejidlo:134274409.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bdj---damejidlo:134277906.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bdt---baedaltong:119448537.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bdt---baedaltong:119446726.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bdt---baedaltong:119444732.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([befbcg---efood-clickdelivery:111421313.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([befbcg---efood-clickdelivery:111422525.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([befbcg---efood-clickdelivery:111391265.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bfa---foodarena:120655247.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bhh---hungryhouse:110965184.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bhh---hungryhouse:110974286.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bhh---hungryhouse:110981659.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([blh---lieferheld:107101250.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([blh---lieferheld:38642300.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([blh---lieferheld:116747487.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bmj---mjam:13244151.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bmj---mjam:117608936.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bmj---mjam:117591065.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bop---onlinepizza:111057681.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bop---onlinepizza:111053874.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bop---onlinepizza:110474939.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpi---pizzade:109893332.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpi---pizzade:107156186.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpi---pizzade:116747870.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpo---pizzaonline:110480720.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpo---pizzaonline:110470289.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpo---pizzaonline:110477448.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpp---pizzaportal:116858697.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpp---pizzaportal:111070353.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpp---pizzaportal:118750618.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpy---pedidosya:110190327.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpy---pedidosya:110191523.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpy---pedidosya:110187139.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bta---talabat:108646433.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bta---talabat:109362366.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([byy---yogiyo-dhh:109287188.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([byy---yogiyo-dhh:108587309.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([byy---yogiyo-dhh:110796642.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY")))
where 
hits.eventInfo.eventAction = 'shop_details.loaded'
group by 1
) B on A.session_id = B.session_id left join
(Select CONCAT(fullVisitorId, STRING(visitId)) as session_id,
From
TABLE_DATE_RANGE([bcd---clickdelivery:110725090.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bcd---clickdelivery:110732352.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bcd---clickdelivery:110731583.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bdj---damejidlo:119446073.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bdj---damejidlo:134274409.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bdj---damejidlo:134277906.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bdt---baedaltong:119448537.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bdt---baedaltong:119446726.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bdt---baedaltong:119444732.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([befbcg---efood-clickdelivery:111421313.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([befbcg---efood-clickdelivery:111422525.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([befbcg---efood-clickdelivery:111391265.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bfa---foodarena:120655247.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bhh---hungryhouse:110965184.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bhh---hungryhouse:110974286.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bhh---hungryhouse:110981659.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([blh---lieferheld:107101250.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([blh---lieferheld:38642300.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([blh---lieferheld:116747487.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bmj---mjam:13244151.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bmj---mjam:117608936.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bmj---mjam:117591065.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bop---onlinepizza:111057681.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bop---onlinepizza:111053874.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bop---onlinepizza:110474939.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpi---pizzade:109893332.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpi---pizzade:107156186.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpi---pizzade:116747870.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpo---pizzaonline:110480720.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpo---pizzaonline:110470289.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpo---pizzaonline:110477448.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpp---pizzaportal:116858697.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpp---pizzaportal:111070353.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpp---pizzaportal:118750618.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpy---pedidosya:110190327.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpy---pedidosya:110191523.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bpy---pedidosya:110187139.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bta---talabat:108646433.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([bta---talabat:109362366.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([byy---yogiyo-dhh:109287188.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([byy---yogiyo-dhh:108587309.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY"))),
TABLE_DATE_RANGE([byy---yogiyo-dhh:110796642.ga_sessions_],TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),-30,"DAY")),TIMESTAMP(DATE_ADD(TIMESTAMP(current_date()),0,"DAY")))
where 
hits.eventInfo.eventAction = 'transaction' 
group by 1
) C
on B.session_id = C.session_id
group by 1,2,3,4,5

ORDER BY NUMBought DESC 